In [1]:
import numpy as np

In [3]:
a = np.random.rand(5,5)

In [4]:
np.argwhere(a > 0.5)

array([[0, 0],
       [1, 0],
       [1, 1],
       [2, 1],
       [2, 3],
       [2, 4],
       [3, 0],
       [3, 3],
       [3, 4],
       [4, 0],
       [4, 4]], dtype=int64)

In [6]:
a > 0.5

array([[ True, False, False, False, False],
       [ True,  True, False, False, False],
       [False,  True, False,  True,  True],
       [ True, False, False,  True,  True],
       [ True, False, False, False,  True]])

In [9]:
{i: i+10 for i in range(10)}.values()

dict_values([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
ss =np.arange(8).reshape((2,4))
ss

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
ss / np.sum(ss, axis=1, keepdims=True)

array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182]])

In [25]:
np.max(ss, axis=0, keepdims=True)

array([[4, 5, 6, 7]])

In [26]:
import nltk

In [5]:
# nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\vlaser\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


True

In [30]:
lemm = nltk.stem.WordNetLemmatizer()

In [3]:
s = 'Dissident UAW members have used the Fiero plant as a symbol of labor-management cooperation'
' '.join([lemm.lemmatize(word) for word in s.split(' ')])


NameError: name 'lemm' is not defined

In [1]:
import nltk

In [6]:
nltk.pos_tag([word for word in s.split(' ')])

[('Dissident', 'NNP'),
 ('UAW', 'NNP'),
 ('members', 'NNS'),
 ('have', 'VBP'),
 ('used', 'VBN'),
 ('the', 'DT'),
 ('Fiero', 'NNP'),
 ('plant', 'NN'),
 ('as', 'IN'),
 ('a', 'DT'),
 ('symbol', 'NN'),
 ('of', 'IN'),
 ('labor-management', 'JJ'),
 ('cooperation', 'NN')]